// <auto-generated />
using AuthorsAndBooksAPI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AuthorsAndBooksAPI.Migrations
{
    [DbContext(typeof(AuthorsBooksApiContext))]
    [Migration("20220720125008_Seedingthedatabase")]
    partial class Seedingthedatabase
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.7");

            modelBuilder.Entity("AuthorsAndBooksAPI.Entities.Author", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Age")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Authors");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Age = "33",
                            Email = "ikenna@gmail.com",
                            FirstName = "Ikenna",
                            LastName = "Ogbonna"
                        },
                        new
                        {
                            Id = 2,
                            Age = "29",
                            Email = "nelson@yahoo.com",
                            FirstName = "Nelson",
                            LastName = "Okoro"
                        },
                        new
                        {
                            Id = 3,
                            Age = "32",
                            Email = "osigwe@gmail.com",
                            FirstName = "Dozie",
                            LastName = "Osigwe"
                        },
                        new
                        {
                            Id = 4,
                            Age = "23",
                            Email = "akinkumi@gmail.com",
                            FirstName = "Akinkumi",
                            LastName = "Ogbonna"
                        });
                });

            modelBuilder.Entity("AuthorsAndBooksAPI.Entities.Book", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AuthorId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasMaxLength(300)
                        .HasColumnType("TEXT");

                    b.Property<string>("ProductionYear")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AuthorId");

                    b.ToTable("Books");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AuthorId = 1,
                            Description = " The depth of our expertise is defined by a carefully selected pool of consultants who ensure that we continue to be the firm of choice to our growing list of discerning clienteles.",
                            ProductionYear = "1990",
                            Title = "Things Fall Apart"
                        },
                        new
                        {
                            Id = 2,
                            AuthorId = 2,
                            Description = "Jobrole Consulting Limited is a Talent Management Company that offers innovative talent and business solutions to drive performance and acceleration. Our focus is to develop and implement new ideas and strategies for Organizations to enhance their business processes and growth.",
                            ProductionYear = "1993",
                            Title = "The beautiful ones are yet to be born"
                        },
                        new
                        {
                            Id = 3,
                            AuthorId = 3,
                            Description = "Our focus is to develop and implement new ideas and strategies for Organizations to enhance their business processes and growth.",
                            ProductionYear = "2000",
                            Title = "The burning man"
                        },
                        new
                        {
                            Id = 4,
                            AuthorId = 4,
                            Description = "The man from another planet is a book written by Akinkumi a renowned writter is about a man that came from another planet, exploits on earth and his love life.",
                            ProductionYear = "2001",
                            Title = "The man from another planet"
                        });
                });

            modelBuilder.Entity("AuthorsAndBooksAPI.Entities.Book", b =>
                {
                    b.HasOne("AuthorsAndBooksAPI.Entities.Author", "Author")
                        .WithMany("Books")
                        .HasForeignKey("AuthorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Author");
                });

            modelBuilder.Entity("AuthorsAndBooksAPI.Entities.Author", b =>
                {
                    b.Navigation("Books");
                });
#pragma warning restore 612, 618
        }
    }
}
